site_name: tutorials
site_description: 'Tutorials'
docs_dir: docs/
repo_name: 'Sinergia-Consortium-Precision-Mapping/tutorials'
repo_url:'https://github.com/Sinergia-Consortium-Precision-Mapping/tutorials'
nav:
  - 'Home': 'index.md'
theme:
  name: 'material'
