site_name: tutorials
site_description: 'Tutorials'
docs_dir: docs/
repo_name: 'Sinergia-Consortium-Precision-Mapping/tutorials'
nav:
  - 'Home': 'index.md'
  - 'About': 'about.md'
  - 'BIDS organization': 'BIDSorganization.md'
  - 'UNIL storage': 'ConnexionUNIL.md'
  - 'FlyWheel Platform': 'Flywheel.md'
  - 'DATALAD': 'Datalad.md'
plugins:
  - mkdocs-video:
      is_video: True
      video_muted: True
      video_controls: True
      css_style:
        width: "50%"
      

theme:
  name: 'Material'
