site_name: tutorials
site_description: 'Tutorials'
docs_dir: docs/
repo_name: 'Sinergia-Consortium-Precision-Mapping/tutorials'
nav:
  - 'Home': 'index.md'
  - 'About': 'about.md'
  - 'BIDS organization': 'BIDSorganization.md'
  - 'UNIL storage': 'ConnexionUNIL.md'
  - 'FlyWheel Platform': 'Flywheel.md'
  - 'DATALAD': 'Datalad.md'
plugins:
  - mkdocs-video:
      is_video: True
      video_muted: True
      video_controls: True
      css_style:
        width: "50%"
  - search: {}
  - encryptcontent:
      title_prefix: ''
      summary: ''
      placeholder: 'Password'
      placeholder_user: User
      password_button_text: 'ENTER'
      decryption_failure_message: 'Wrong user name or password.'
      encryption_info_message: 'Legitimation required.'
      #html_template_path: "decrypt-form.tpl.html" # override default html template
      password_button: True
      input_class: 'w3-input' # CSS class used for input username and password
      button_class: 'w3-button w3-theme-l1 w3-hover-theme' # CSS class for password_button
      hljs: False
      arithmatex: False
      mermaid2: False
      remember_keys: false # keys from keystore will temporarily saved to sessionStorage
      remember_password: false # the entered credentials are not saved
      remember_prefix: encryptcontent_plugin_ # use different prefixes if other sites are running on the same domain
      encrypted_something: # additionally encrypt some html elements
        myToc: [div, id]
        myTocButton: [div, id]
      search_index: 'dynamically' # dynamically encrypt mkdocs search index 
      webcrypto: true # use browsers webcrypto support
      password_file: 'passwords.yml' # file with password inventory
      sign_files: 'encryptcontent-plugin.json' # save ed25519 signatures here
      hash_filenames: # add hash to file names of assets (to make them impossible to guess
        extensions:
          - 'png'
          - 'jpg'
          - 'jpeg'
          - 'svg'
        except:
          - 'logo.svg'
      

theme:
  name: 'readthedocs'
