site_name: tutorials
site_description: 'Tutorials'
docs_dir: docs/
repo_name: 'Sinergia-Consortium-Precision-Mapping/tutorials'
nav:
  - 'Home': 'index.md'
  - 'About': 'about.md'
plugins:
  - mkdocs-video:
      is_video: True
      video_muted: True
      video_controls: True

theme:
  name: 'material'
