site_name: tutorials
site_description: 'Tutorials'
docs_dir: docs/
repo_name: 'Sinergia-Consortium-Precision-Mapping/tutorials'
nav:
  - 'Home': 'index.md'
  - 'About': 'about.md'
  - 'BIDS organization': 'BIDSorganization.md'
  - 'UNIL storage': 'ConnexionUNIL.md'
  - 'FlyWheel Platform': 'Flywheel.md'
  - 'DATALAD': 'Datalad.md'
plugins:
  - mkdocs-video:
      is_video: True
      video_muted: True
      video_controls: True
      css_style:
        width: "50%"
  - search: {}
  - encryptcontent:
      global_password: 'Sinergia2023'
      title_prefix: '[LOCK]'
      summary: 'This website is for SINERGIA collaborator only. Please provide the password to access the content.'
      encryption_info_message: 'Wrong password'
      input_class: 'md-search__form md-search__input'
      button_class: 'md-search__icon' 


theme:
  name: 'readthedocs'
