site_name: tutorials
site_description: 'Tutorials'
docs_dir: docs/
repo_name: 'Sinergia-Consortium-Precision-Mapping/tutorials'
nav:
  - 'Home': 'index.md'
  - 'About': 'about.md'
  - 'BIDS organization': 'BIDSorganization.md'
  - 'UNIL storage': 'ConnexionUNIL.md'
  - 'FlyWheel Platform': 'Flywheel.md'
  - 'DATALAD': 'Datalad.md'
plugins:
  - mkdocs-video:
      is_video: True
      video_muted: True
      video_controls: True
      css_style:
        width: "50%"
  - search: {}
  - encryptcontent:
      global_password: 'Sinergia2023'
      title_prefix: '[PROTECTED]'
      summary: 'This website is for SINERGIA collaborator only. '
      encryption_info_message: 'Please provide the password to access the content.'
      input_class: 'md-search__form md-search__input'
      button_class: 'md-search__icon' 
      password_button: True
      #input_class: 'w3-input' # CSS class used for input username and password
      #button_class: 'w3-button w3-theme-l1 w3-hover-theme' # CSS class for password_button
      remember_password: false

theme:
  name: 'readthedocs'
