site_name: tutorials
site_description: 'Tutorials'
docs_dir: docs/
repo_name: 'Sinergia-Consortium-Precision-Mapping/tutorials'
nav:
  - 'Home': 'index.md'
  - 'Open Science': 'OpenScience.md'
  - 'BIDS organization': 'BIDSorganization.md'
  - 'UNIL storage': 'ConnexionUNIL.md'
  - 'FlyWheel Platform': 'Flywheel.md'
  - 'DATALAD': 'Datalad.md'
plugins:
  - mkdocs-video:
      is_video: True
      video_muted: True
      video_controls: True
      css_style:
        width: "50%"
  - search: {}
  - encryptcontent:
      global_password: 'Sinergia2023'
      title_prefix: ''
      summary: 'This website is for SINERGIA collaborator only. '
      encryption_info_message: 'Please provide the password to access the content.'
      remember_password: false

markdown_extensions:
  - attr_list
  - md_in_html

theme:
  name: 'material'
  palette:
    accent: 'dark'
    primary: 'teal'

