name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - "**.md"
      - "mkdocs.yml"
  workflow_dispatch:
  
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - uses: actions/setup-python@v3
      - run: pip install --upgrade pip && pip install mkdocs mkdocs-gen-files mkdocs-material
      - run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Build site (_site directory name is used for Jekyll compatiblity)
        run: mkdocs build --config-file ./mkdocs.yml --site-dir ./_site
      - name: Publish docs
        run: mkdocs gh-deploy

deploy:
  environment:
     name: github-pages
     url: ${{ steps.deployment.outputs.page_url }}
  runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2